import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";
import * as p from "@clack/prompts";
import { promptForTargets } from "./prompt.js";
import type { CliOptions, StoredConfig, ResolvedConfig } from "./types.js";

/** Well-known agent skills directories, in priority order. */
const KNOWN_SKILLS_DIRS = [
  ".agents/skills",
  ".claude/skills",
];

/** Well-known target instruction files. */
const KNOWN_TARGETS = ["CLAUDE.md", "AGENTS.md"];

/** Default section heading for the injection block. */
export const DEFAULT_HEADING = "Skill Instructions";

/** Default description paragraph after the heading. */
export const DEFAULT_DESCRIPTION =
  "The following instructions come from installed skills (autogenerated, do not edit manually) and should always be followed.";

/** Check if a path exists on disk. */
async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

/** Load config from .skills-inject.json or package.json. */
export async function loadConfig(cwd: string): Promise<StoredConfig | null> {
  // Try .skills-inject.json first.
  const configPath = join(cwd, ".skills-inject.json");
  try {
    const raw = await readFile(configPath, "utf-8");
    return JSON.parse(raw) as StoredConfig;
  } catch {
    // Not found or invalid — try package.json.
  }

  const pkgPath = join(cwd, "package.json");
  try {
    const raw = await readFile(pkgPath, "utf-8");
    const pkg = JSON.parse(raw) as Record<string, unknown>;
    if (pkg["skills-inject"] && typeof pkg["skills-inject"] === "object") {
      return pkg["skills-inject"] as StoredConfig;
    }
  } catch {
    // No package.json or no config.
  }

  return null;
}

/** Detect which skills directories exist on disk. */
export async function detectSkillsDirs(cwd: string): Promise<string[]> {
  const found: string[] = [];
  for (const dir of KNOWN_SKILLS_DIRS) {
    if (await exists(join(cwd, dir))) {
      found.push(dir);
    }
  }
  return found;
}

/** Detect which target instruction files exist on disk. */
export async function detectTargets(cwd: string): Promise<string[]> {
  const found: string[] = [];
  for (const target of KNOWN_TARGETS) {
    if (await exists(join(cwd, target))) {
      found.push(target);
    }
  }
  return found;
}

/** Print a warning when no skills directories are found. */
function printNoSkillsDirsWarning(): void {
  p.log.error(
    "No skills directories found. Looked for:\n" +
    "  - .agents/skills/\n" +
    "  - .claude/skills/\n\n" +
    "Install skills first with: npx skills add <repo>\n" +
    "Or specify a directory with: npx skills-inject --skills-dir <path>",
  );
}

async function resolveSkillsDirs(
  options: CliOptions,
  storedConfig: StoredConfig | null,
  cwd: string,
): Promise<string[]> {
  if (options.skillsDirs.length > 0) return options.skillsDirs;
  if (storedConfig?.skillsDirs && storedConfig.skillsDirs.length > 0) return storedConfig.skillsDirs;
  return detectSkillsDirs(cwd);
}

async function resolveTargets(
  options: CliOptions,
  storedConfig: StoredConfig | null,
  cwd: string,
): Promise<{ targets: string[]; prompted: boolean }> {
  if (options.targets.length > 0) return { targets: options.targets, prompted: false };
  if (storedConfig?.targets && storedConfig.targets.length > 0) return { targets: storedConfig.targets, prompted: false };

  const detected = await detectTargets(cwd);
  if (detected.length === 1) return { targets: detected, prompted: false };
  if (detected.length > 1) return { targets: await promptForTargets("both"), prompted: true };
  return { targets: await promptForTargets("neither"), prompted: true };
}

/**
 * Resolve all configuration from CLI options, stored config, and auto-detection.
 * Returns the resolved config and whether the user was prompted interactively.
 * Exits the process if no skills directories are found.
 */
export async function resolveConfig(
  options: CliOptions,
  storedConfig: StoredConfig | null,
  cwd: string,
): Promise<{ config: ResolvedConfig; prompted: boolean }> {
  const skillsDirs = await resolveSkillsDirs(options, storedConfig, cwd);

  if (skillsDirs.length === 0) {
    printNoSkillsDirsWarning();
    process.exit(1);
  }

  const { targets, prompted } = await resolveTargets(options, storedConfig, cwd);

  return {
    config: {
      skillsDirs,
      targets,
      heading: storedConfig?.heading ?? DEFAULT_HEADING,
      description: storedConfig?.description ?? DEFAULT_DESCRIPTION,
    },
    prompted,
  };
}
